### PR TITLE
Rmarkdown integration

### PR DESCRIPTION
**Pull request by jcheng5**
Allows an alternate email authoring experience (than `compose_email()`), using R Markdown.

Create an .Rmd file, with `output: blastula::blastula_email`. (No need to use `add_image` or `add_ggplot`, instead use traditional knitr/rmd techniques for embedding images and plots.)

    ---
    output: blastula::blastula_email
    ---
    
    ## Here is your daily report, fresh in your inbox!

    ```{r}
    plot(stuff)
    ```

Then call `render_email(filepath)` to create a blastula email object. 

You can call `attach_email(render_email(filepath))` from within an R Markdown document running on RStudio Connect; this will cause the email to be sent as a byproduct of the render. (Just make sure that when publishing the host/report Rmd, to include the child/email Rmd in the bundle.)

When calling `render_email` from within a host Rmd, you have access to any variables and chunks that were executed up to that point (and I assume--but have not verified--that any variables created during email Rmd rendering will also be available back in the host Rmd when execution continues). On the downside, you cannot define code chunks in the email Rmd that have the same names and code chunks in the host Rmd.

For example, if this appears in the host Rmd:

    ```{r summary}
    summary(df)
    ```

then this cannot appear in the email Rmd:

    ```{r summary}
    summary(df)
    ```

_However_, you can do this from the email Rmd:

    ```{r summary}
    ```

which will cause the output from the `summary` chunk in the host Rmd to appear here, without needing to reexecute the chunk!

## TODO

- [ ] Remove options that can't possibly work, from `blastula_email` (i.e. any of them that require JavaScript or external resources)
- [ ] Perform URL decoding/encoding when interpreting and replacing img src references
- [ ] Respect `file://` URLs, absolute file paths
- [x] Remove implementation of `knit_print.blastula_message` that attaches the email; @rich-iannone thought it'd be better to force users to make this explicit with `attach_email(msg)`.

### CODE REVIEW

**Comment by rich-iannone** [comment]
Looks great, thanks for all the work on this!

**Comment by Nicktz** [comment]
Hi guys, very excited about this being standardized in rmarkdown. @jcheng5 is there a beta version we can try using the new integrated features? Also, I assume most people will use this with Outlook - please do testing on it as the emails (figures, html tables) do not render well on Outlook (as opposed to gmail). I have to, e.g., use knitr::imgur_upload to put images on imgur, and point to it in the email (i.e. have it be external, not embedded figures). Perhaps consider making this optional in figure chunks (adding an imgur option) if the issues with Outlook persist. Otherwise, blastula works well in other email environments and adding it to rmarkdown directly is a great idea!

**Comment by jcheng5** [comment]
Ack there were still some open TODOs, I didn't mean for you to merge. Guess I should have put "WIP" in the title. 

@Nicktz Are you sending through blastula directly or RStudio Connect when you have problems with images in Outlook?

**Comment by Nicktz** [comment]
@jcheng5 I am currently sending the blastula object (Msg$html_html) using RDCOMClient. Is there another / better way to send it through Outlook? I really think for this to have broad uptake the emails should be Outlook ready (unfortunately this is stock standard for business use). It is quite a hack to get it sent atm.

**Pull request merged**
